### ISSUE TITLE
Failed to launch Dwarf Fortress when using Konsole

### ISSUE THREAD

**Issue by AntiSC2** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#56]
When I select my terminal to be konsole it fails to launch dwarf fortress with the following error:
```
Traceback (most recent call last):
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/core.launcher", line 91, in run_program
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/core.terminal", line 25, in get_terminal_command
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/core.terminal", line 124, in get_command_line
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/subprocess", line 566, in check_output
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/subprocess", line 710, in __init__
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/subprocess", line 1335, in _execute_child
OSError: [Errno 2] No such file or directory
ERROR: Could not launch `./df_linux/dfhack`
```
Setting it up with a the custom command: `konsole -e $` and running the test gives the following output:
```
Terminal succesfully started! Test will begin in 3 seconds.
Launching child process...
Waiting for child process to start...
konsole: symbol lookup error: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```
Setting the terminal to urxvt works fine without any problems and before I installed KDE it also worked fine with gnome-terminal. Also, launching dfhack manually with konsole works without any problems. It is only when you launch df through PyLNP with konsole that it fails.

System info:
- OS: Solus 3.999 64-bit
- Kernel: 4.15.17
- KDE Plasma: 5.12.4
- Qt: 5.10.0
- Konsole 17.12.3
- Freetype 2.8
- harfbuzz 1.7.5

**Comment by BrunoDSL** [comment]
Confirming this error also happens in Arch Linux. DF launches normally if you run it or if you run dfhack, but not when you run it from LNP. All the errors are exactly the same.

**Comment by BrunoDSL** [comment]
The following error happens in KDE Neon (Ubuntu 18.04) when you attempt to run DFHack:

```./dfhack[distro_fixes] [INFO] Checking whether any distro specific fixes are required...
[distro_fixes] [INFO] OS: neon
[distro_fixes] [INFO] ARCH: x86_64
[distro_fixes] [INFO] VER: 18.04
[distro_fixes] [INFO] DF_ARCH: 64-bit
[distro_fixes] [INFO] DF_BIN_LOCATION: ./libs/Dwarf_Fortress
[distro_fixes] [WARN] 64bit 'Dwarf_Fortress' on unhandled 64bit OS detected. If you get 'missing file' errors, please open an issue on Github: https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues.
[distro_fixes] [WARN] Could not find a 64-bit zlib
[distro_fixes] [INFO] PRELOAD_LIB: 
[distro_fixes] [INFO] LD_LIBRARY_PATH: 
[distro_fixes] [INFO] Done
./libs/Dwarf_Fortress: error while loading shared libraries: libgraphics.so: wrong ELF class: ELFCLASS32```

**Comment by lethosor** [comment]
You either have 32-bit Dwarf Fortress or 32-bit libs/libgraphics.so somehow.

**Comment by BrunoDSL** [comment]
> You either have 32-bit Dwarf Fortress or 32-bit libs/libgraphics.so somehow.

That only seem to happen if you replace the file from the base install with the latest release link on the releases page. When you just use the version provided in the download link, the same error the OP posted happens.

**Comment by lethosor** [comment]
I don't know what links you're talking about. In the case of the original post, does "./df_linux/dfhack" exist?

**Comment by BrunoDSL** [comment]
- Download LNP normally.
- Go to the "Releases" page, download the topmost release, then extract and replace the files that came with LNP with the ones from that file.

That's how you get the particular error.

In case of the original post, not only does dfhack exist, but the game launches normally if you run it(from the console, not using the LNP GUI). The only instance in which that error happens is when you attempt to run the game by clicking on the "Play Dwarf Fortress!" button.

Now, I have another installation with DFHack installed manually and for Konsole, DFHack crashes Dwarf Fortress if you just open the `dfhack` file a few seconds after the version number appears in the game (assuming you disabled the intro and sounds. If you didn't, the game crashes right after the Bay12 intro is done displaying and playing the "Beyond Quality!" sound.) at least for Konsole, `dfhack` has to be run as `konsole -e "<path to your df installation>/dfhack"` for it to work properly. I just tested on here by setting `konsole -e $` as a custom command instead of just the `KDE` option and, at least in my case, the game runs normally and no errors are reported. The same if you use `xterm` instead.

**Comment by magicalraccoon** [comment]
+1 that using `konsole -e $` in the custom terminal command section works for me

**Comment by yahvk-cuna** [comment]
+1
When using `konsole -e $`, terminal test will get error
```
konsole: symbol lookup error: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var
```
but the game works.

**Comment by HarleyLorenzo** [comment]
konsole -e $ as a custom terminal command fails to work for me on Ubuntu 19.04, and it still gives me the same error of `ERROR: Could not launch ./df_linux/dfhack`

I'm using xterm for the time being, but I would like to find a work around

**Comment by Crafol** [comment]
gnome-terminal -- $
